[package]
name = "mono_lib"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
winapi = { version = "0.3.8", features = ["consoleapi", "minwindef", "libloaderapi", "fileapi", "handleapi"] }
libc = "0.2.115"
[lib]
crate-type = ["cdylib"]

